version: "3.8"

services:

  traefik:
    image: traefik:v2.4
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesResolvers.letsencrypt.acme.email=cale@modtechgroup.com"
      - "--certificatesResolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesResolvers.letsencrypt.acme.tlsChallenge=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Traefik Dashboard (optional, but useful for debugging)
    networks:
      - default
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/letsencrypt:/letsencrypt"
    restart: always

  frontend:
    image: quivr-frontend-prebuilt
    pull_policy: never
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_ENV=local
        - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        - NEXT_PUBLIC_CMS_URL=${NEXT_PUBLIC_CMS_URL}
        - NEXT_PUBLIC_FRONTEND_URL=${NEXT_PUBLIC_FRONTEND_URL}
    container_name: web
    depends_on:
      - backend-core
    restart: always
    networks:
      - default

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`wildcatgpt.com`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"

  backend-core:
    image: stangirard/quivr-backend-prebuilt:latest
    pull_policy: if_not_present
    env_file:
      - .env
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend-core
    healthcheck:
      test: ["CMD", "curl", "http://localhost:5050/healthz"]
    command:
      - "uvicorn"
      - "main:app"
      - "--reload"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "5050"
      - "--workers"
      - "6"
    restart: always
    volumes:
      - ./backend/:/code/
    networks:
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-core.rule=Host(`wildcatgpt.com`) && PathPrefix(`/backend_core`)"
      - "traefik.http.routers.backend-core.entrypoints=websecure"
      - "traefik.http.routers.backend-core.tls.certresolver=letsencrypt"
      - "traefik.http.services.backend-core.loadbalancer.server.port=5050"
      - "traefik.http.middlewares.backend-core-stripprefix.stripprefix.prefixes=/backend_core"
      - "traefik.http.routers.backend-core.middlewares=backend-core-stripprefix"

  redis:
    image: redis:latest@sha256:a7cee7c8178ff9b5297cb109e6240f5072cdaaafd775ce6b586c3c704b06458e
    container_name: redis
    restart: always
    networks:
      - default

  worker:
    pull_policy: if_not_present
    image: stangirard/quivr-backend-prebuilt:latest
    env_file:
      - .env
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: worker
    command: celery -A celery_worker worker -l info
    restart: always
    depends_on:
      - redis

  beat:
    image: stangirard/quivr-backend-prebuilt:latest
    pull_policy: if_not_present
    env_file:
      - .env
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: beat
    command: celery -A celery_worker beat -l info
    restart: always
    depends_on:
      - redis

  flower:
    image: stangirard/quivr-backend-prebuilt:latest
    pull_policy: if_not_present
    env_file:
      - .env
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: flower
    command: celery -A celery_worker flower -l info --port=5555
    restart: always
    depends_on:
      - redis
      - worker
      - beat
    networks:
      - default

networks:
  default:
    name: web
    external: false
